from fpdf import FPDF
import datetime
import os

class PDFReportGenerator(FPDF):
    def header(self):
        # Branding Header (AnalytixAI Midnight Luxe)
        self.set_fill_color(0, 0, 0) 
        self.rect(0, 0, 210, 30, 'F')
        
        # Logo Text
        self.set_font('helvetica', 'B', 18)
        self.set_text_color(255, 255, 255)
        self.set_y(10)
        self.cell(0, 10, '  AnalytixAI', border=False, align='L')
        
        # Global Identifiers
        self.set_font('helvetica', 'B', 8)
        self.set_text_color(255, 255, 255) # Pure White
        self.set_y(10)
        self.cell(0, 5, 'EXECUTIVE INTELLIGENCE ASSESSMENT  ', border=False, align='R', ln=True)
        self.set_text_color(161, 161, 170) # Zinc-400
        self.cell(0, 5, 'AI-GENERATED REPORT | v2.0  ', border=False, align='R')
        
        # Confidential Watermark
        self.set_font('helvetica', 'B', 40)
        self.set_text_color(240, 240, 240)
        self.set_y(150)
        self.set_x(30)
        self.rotate(45, 105, 150)
        self.cell(0, 0, 'ANALYTIXAI - STRICTLY CONFIDENTIAL', border=False, align='C')
        self.rotate(0)
        
        self.ln(25)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f'Page {self.page_no()} | Generated on {datetime.datetime.now().strftime("%Y-%m-%d")} | Authenticity Verified', align='C')

    def clean_text(self, text):
        """
        Strips emojis and other non-latin characters that Helvetica doesn't support.
        """
        if not text: return ""
        # Convert to string if it's not
        text = str(text)
        # fpdf only supports latin-1 by default
        return text.encode('latin-1', 'replace').decode('latin-1')

    def draw_highlight_box(self, title, text, type="insight"):
        # Box Colors
        if type == "risk":
            bg = (250, 250, 250); border = (39, 39, 42); text_col = (0, 0, 0); icon = "!"
        elif type == "rec":
            bg = (255, 255, 255); border = (39, 39, 42); text_col = (0, 0, 0); icon = ">>"
        else:
            bg = (244, 244, 245); border = (39, 39, 42); text_col = (0, 0, 0); icon = "*"

        self.set_fill_color(*bg)
        self.set_draw_color(*border)
        self.set_line_width(0.5)
        self.rect(self.get_x(), self.get_y(), 190, 25, 'FD')
        
        self.set_xy(self.get_x() + 5, self.get_y() + 5)
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(*text_col)
        self.cell(0, 5, self.clean_text(f"{icon} {title.upper()}"), ln=True)
        
        self.set_font('helvetica', '', 9)
        self.set_x(self.get_x() + 5)
        self.multi_cell(180, 5, self.clean_text(text))
        self.ln(10)

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 16)
        self.set_text_color(0, 0, 0)
        self.cell(0, 15, self.clean_text(title), ln=True)
        self.set_draw_color(39, 39, 42)
        self.line(self.get_x(), self.get_y(), self.get_x() + 40, self.get_y())
        self.ln(5)

    def chapter_body(self, paragraphs):
        self.set_font('helvetica', '', 11)
        self.set_text_color(71, 85, 105)
        if isinstance(paragraphs, str):
            paragraphs = [paragraphs]
        if not paragraphs: return
        for p in paragraphs:
            if p:
                self.multi_cell(0, 6, self.clean_text(p))
                self.ln(2)
        self.ln(5)

    def generate(self, report_data, filepath):
        self.add_page()
        
        # 1. COVER PAGE
        self.set_fill_color(0, 0, 0)
        self.rect(0, 0, 210, 297, 'F')
        
        self.set_y(100)
        self.set_font('helvetica', 'B', 42)
        self.set_text_color(255, 255, 255)
        self.cell(0, 20, 'INTELLIGENCE', ln=True, align='C')
        self.set_font('helvetica', '', 20)
        self.cell(0, 15, 'Strategic Multi-Variant Analysis Report', ln=True, align='C')
        
        self.set_y(200)
        self.set_font('helvetica', 'B', 14)
        self.cell(0, 10, self.clean_text(f"DATASET: {report_data.dataset_name}"), ln=True, align='C')
        self.set_font('helvetica', '', 10)
        self.set_text_color(161, 161, 170)
        self.cell(0, 10, f"Generated by AnalytixAI Autonomous Engine", ln=True, align='C')

        # 2. EXECUTIVE SUMMARY
        self.add_page()
        self.chapter_title("1. Executive Strategic Narrative")
        if report_data.sections and len(report_data.sections) > 0:
            self.chapter_body(report_data.sections[0].content)

        # 3. SECTIONS
        for i, section in enumerate(report_data.sections[1:], 2):
            self.add_page()
            self.chapter_title(f"{i}. {section.title}")
            self.chapter_body(section.content)
            
            # Metrics / Tables
            if section.metrics:
                if isinstance(section.metrics, dict):
                    if section.metrics.get("type") == "leaderboard":
                        self.set_font('helvetica', 'B', 10)
                        self.cell(0, 10, "Model Performance Leaderboard", ln=True)
                        self.set_font('helvetica', '', 9)
                        # Simplified table
                        for row in section.metrics.get("data", []):
                            self.cell(60, 8, self.clean_text(str(row[1])), border=1)
                            self.cell(60, 8, self.clean_text(str(row[2])), border=1, ln=True)
                    elif section.metrics.get("type") == "data_preview":
                        self.set_font('helvetica', 'B', 10)
                        self.cell(0, 10, "Final Dataset Preview (Top 10 Rows)", ln=True)
                        self.set_font('helvetica', '', 7)
                        cols = section.metrics.get("columns", [])[:6] # Limit to 6 cols for width
                        for col in cols:
                            self.cell(30, 8, self.clean_text(str(col)), border=1)
                        self.ln()
                        for row in section.metrics.get("data", []):
                            for val in row[:6]:
                                self.cell(30, 8, self.clean_text(str(val)), border=1)
                            self.ln()
                    else:
                        # Standard Key-Value table
                        self.set_font('helvetica', 'B', 9)
                        for k, v in section.metrics.items():
                            if isinstance(v, (str, int, float)):
                                self.cell(50, 8, self.clean_text(str(k)), border=1)
                                self.cell(140, 8, self.clean_text(str(v)), border=1, ln=True)

        self.output(filepath)
