from fpdf import FPDF
from app.core.reporting.report_schema import FullReport

class PDFReportGenerator(FPDF):
    def header(self):
        # Branding Header
        self.set_font('helvetica', 'B', 12)
        self.set_text_color(40, 70, 150)
        self.cell(0, 10, 'AnalytixAI | Autonomous Intelligence Platform', border=False, align='L')
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, 'BOARDROOM READY', border=False, align='R')
        self.ln(15)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by AnalytixAI Autonomous Engine', align='C')

    def chapter_title(self, title):
        self.set_font('helvetica', 'B', 14)
        self.set_fill_color(240, 245, 255)
        self.set_text_color(40, 70, 150)
        self.cell(0, 8, f' {title}', fill=True, ln=True)
        self.ln(4)

    def chapter_body(self, paragraphs):
        self.set_font('helvetica', '', 11)
        self.set_text_color(50, 50, 50)
        for p in paragraphs:
            # Handle basic encoding
            txt = p.encode('latin-1', 'replace').decode('latin-1')
            
            if txt.strip().startswith("- "):
                self.set_x(15)
                self.multi_cell(0, 6, txt)
            else:
                self.set_x(10)
                self.multi_cell(0, 6, txt)
            self.ln(1)
        self.ln(2)

    def draw_table(self, data_dict):
        """
        Custom table drawer for quality metrics and data previews.
        """
        if not isinstance(data_dict, dict): return
        
        # 1. Check for Data Preview Type
        if data_dict.get("type") == "data_preview":
            columns = data_dict.get("columns", [])
            data_rows = data_dict.get("data", [])
            
            if not columns or not data_rows: return
            
            # Limit to top 6 columns for PDF width
            display_cols = columns[:6]
            col_width = 190 / len(display_cols)
            
            self.set_font('helvetica', 'B', 8)
            self.set_fill_color(230, 240, 255)
            for col in display_cols:
                self.cell(col_width, 7, str(col)[:15], border=1, fill=True, align='C')
            self.ln()
            
            self.set_font('helvetica', '', 7)
            for row in data_rows:
                for i in range(len(display_cols)):
                    val = str(row[i]) if i < len(row) else ""
                    self.cell(col_width, 6, val[:20], border=1)
                self.ln()
            
            if len(columns) > 6:
                self.set_font('helvetica', 'I', 7)
                self.cell(0, 6, f"* Showing first 6 of {len(columns)} columns.", align='L', ln=True)
            return

        # 2. Check if it's column_info (dict of dicts)
        first_val = next(iter(data_dict.values())) if data_dict else None
        
        if isinstance(first_val, dict):
            # Column Quality Table
            headers = ["Feature", "Type", "Missing", "Unique", "Outliers", "Status"]
            col_widths = [45, 30, 25, 25, 25, 30]
            
            self.set_font('helvetica', 'B', 10)
            self.set_fill_color(230, 230, 230)
            for i, h in enumerate(headers):
                self.cell(col_widths[i], 8, h, border=1, fill=True, align='C')
            self.ln()
            
            self.set_font('helvetica', '', 9)
            for col, info in list(data_dict.items())[:15]: # Limit to top 15 columns
                self.cell(col_widths[0], 7, str(col)[:20], border=1)
                self.cell(col_widths[1], 7, str(info.get('dtype', 'N/A')), border=1, align='C')
                self.cell(col_widths[2], 7, f"{info.get('missing_count', 0)}", border=1, align='C')
                self.cell(col_widths[3], 7, f"{info.get('unique_count', 0)}", border=1, align='C')
                self.cell(col_widths[4], 7, f"{info.get('outlier_count', 0)}", border=1, align='C')
                
                status = "Warning" if info.get('missing_count', 0) > 0 or info.get('is_constant') else "Pass"
                if status == "Warning": self.set_text_color(200, 0, 0)
                self.cell(col_widths[5], 7, status, border=1, align='C')
                self.set_text_color(50, 50, 50)
                self.ln()
            
            if len(data_dict) > 15:
                self.set_font('helvetica', 'I', 8)
                self.cell(0, 7, f"... and {len(data_dict)-15} more columns.", align='L', ln=True)
        else:
            # Simple Key-Value Table
            self.set_font('helvetica', 'B', 10)
            self.set_fill_color(245, 245, 245)
            for k, v in data_dict.items():
                self.cell(60, 7, str(k), border=1, fill=True)
                self.cell(100, 7, str(v), border=1, ln=True)
        self.ln(5)

    def generate(self, report_data: FullReport, filepath: str):
        self.add_page()
        
        # Title Page Info
        self.set_y(60)
        self.set_font('helvetica', 'B', 28)
        self.set_text_color(40, 70, 150)
        self.cell(0, 20, report_data.title, align='C', ln=True)
        
        self.ln(10)
        self.set_font('helvetica', '', 16)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, f"Autonomous Intelligence Assessment", align='C', ln=True)
        self.cell(0, 10, f"Project: {report_data.dataset_name}", align='C', ln=True)
        
        self.set_y(150)
        self.set_font('helvetica', 'B', 12)
        self.cell(0, 10, "STRICTLY CONFIDENTIAL", align='C', ln=True)
        self.ln(50)
        
        # Sections
        for section in report_data.sections:
            if self.get_y() > 230: self.add_page() # Page break if near bottom
            self.chapter_title(section.title)
            self.chapter_body(section.content)
            
            if section.metrics:
                self.draw_table(section.metrics)
                
        self.output(filepath)
